/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//profile'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//profile': RouteRecordInfo<
      '//profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/admin/(index)': RouteRecordInfo<
      '/admin/(index)',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/groups': RouteRecordInfo<
      '/admin/groups',
      '/admin/groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/shares': RouteRecordInfo<
      '/admin/shares',
      '/admin/shares',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system': RouteRecordInfo<
      '/admin/system',
      '/admin/system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//profile'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/profile.vue': {
      routes:
        | '//profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/admin/(index).vue': {
      routes:
        | '/admin/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/groups.vue': {
      routes:
        | '/admin/groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/shares.vue': {
      routes:
        | '/admin/shares'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system.vue': {
      routes:
        | '/admin/system'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
